// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QBay8eJ2PEqZVlZSz4EsLBws1lKZ1jA',
    appId: '1:582189956187:web:310bcc4db70490c94d937e',
    messagingSenderId: '582189956187',
    projectId: 'zartek-food-app',
    authDomain: 'zartek-food-app.firebaseapp.com',
    databaseURL: 'https://zartek-food-app-default-rtdb.firebaseio.com',
    storageBucket: 'zartek-food-app.appspot.com',
    measurementId: 'G-FTPWQMNLP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuhYdA3o06TtnpfBGzU1_8xuoMzL-PvjQ',
    appId: '1:582189956187:android:67dd042a618ec55f4d937e',
    messagingSenderId: '582189956187',
    projectId: 'zartek-food-app',
    databaseURL: 'https://zartek-food-app-default-rtdb.firebaseio.com',
    storageBucket: 'zartek-food-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhKS7sRBQOUDoVhBuiO1aT_Ngaj1UHHjU',
    appId: '1:582189956187:ios:cfc756d09c3aabe64d937e',
    messagingSenderId: '582189956187',
    projectId: 'zartek-food-app',
    databaseURL: 'https://zartek-food-app-default-rtdb.firebaseio.com',
    storageBucket: 'zartek-food-app.appspot.com',
    iosBundleId: 'com.example.zartek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhKS7sRBQOUDoVhBuiO1aT_Ngaj1UHHjU',
    appId: '1:582189956187:ios:cfc756d09c3aabe64d937e',
    messagingSenderId: '582189956187',
    projectId: 'zartek-food-app',
    databaseURL: 'https://zartek-food-app-default-rtdb.firebaseio.com',
    storageBucket: 'zartek-food-app.appspot.com',
    iosBundleId: 'com.example.zartek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7QBay8eJ2PEqZVlZSz4EsLBws1lKZ1jA',
    appId: '1:582189956187:web:14bfe617eb65da654d937e',
    messagingSenderId: '582189956187',
    projectId: 'zartek-food-app',
    authDomain: 'zartek-food-app.firebaseapp.com',
    databaseURL: 'https://zartek-food-app-default-rtdb.firebaseio.com',
    storageBucket: 'zartek-food-app.appspot.com',
    measurementId: 'G-1LCFXP6DK7',
  );

}